CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	[Email] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(111) NOT NULL,
	[FirstName] VARCHAR(50) NOT NULL,
	[LastName] VARCHAR(50) NOT NULL,
	CONSTRAINT [UC_Email] UNIQUE ([Email])
)
